import Image from "next/image";

export const metadata = {
  title: "Services",
  description: "Generated by create next app",
};

export default function ServicePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Servicios</h1>
    </main>
  )
}
