import Image from "next/image";

export const metadata = {
  title: "Transfers",
  description: "Generated by create next app",
};

export default function TransferPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Traslados</h1>
    </main>
  );
}
