import { inter } from './fonts';
import "./globals.css";
// Archivo padre que contiene todas las páginas
//todo lo que ponga acá se verá en todas las páginas
// componentes globales




export const metadata = {
  title: "Digital Identity App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
