import { Inter } from "next/font/google";
import "./globals.css";
// Archivo padre que contiene todas las páginas
//todo lo que ponga acá se verá en todas las páginas
// componentes globales


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
