export const metadata = {
  title: "Contests",
  description: "Generated by create next app",
};

export default function ContestPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Concursos</h1>
    </main>
  );
}
