// Archivo padre que contiene todas las páginas
//todo lo que ponga acá se verá en todas las páginas
// componentes globales

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className='flex'>
      <div className='w-1/3'>sidebar</div>
      <div className='w-2/3'>{children}</div>
    </div>
    
  );
}
