import Image from "next/image";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Dashboard</h1>
    </main>
  )
}
