export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
}

export default function DashboardPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Aquí puedes realizar tus transacciones</h1>
    </main>
  )
}
